name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Run tamper check
      run: python -c "from integrity_core import TamperChecker; import sys; success, violations = TamperChecker().check(); sys.exit(0 if success else 1)"
    
    - name: Run trivial test check
      run: python -c "from integrity_core import TrivialTestChecker; import sys; success, violations = TrivialTestChecker().check(); sys.exit(0 if success else 1)"
    
    - name: Run tests with coverage
      run: |
        pytest --cov=src --cov-report=xml --cov-report=term-missing --fail-under=80
    
    - name: Run diff coverage check
      run: python -c "from integrity_core import DiffCoverageChecker; import sys; success, violations = DiffCoverageChecker().check(); sys.exit(0 if success else 1)"
    
    - name: Run policy check
      run: python -c "from integrity_core import PolicyChecker; import sys; success, violations = PolicyChecker().check({}); sys.exit(0 if success else 1)"
    
    - name: Run no-skip check
      run: python -c "import subprocess; result = subprocess.run(['pytest', '--collect-only', '-q'], capture_output=True, text=True); assert 'SKIPPED' not in result.stdout and 'xfail' not in result.stdout, 'Found skipped or xfail tests'"
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
