apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prompt-ops-hub.fullname" . }}
  labels:
    {{- include "prompt-ops-hub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "prompt-ops-hub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "prompt-ops-hub.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: {{ .Values.database.url | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }} 